import { useEffect, useMemo, useState } from "react";
import { supabase } from "./supabase";
import { assessmentToRegistrationDraft, CLASSIFICATION_QUESTIONS, classifyResource } from "./classification";
import { PROPRIETARY_NOTICE, SHORT_PROPRIETARY_NOTICE } from "./lifecycles";
import { LifecycleExperience } from "./LifecycleWorkspace";

const Pill = ({ value }) => <span className={`pill ${value}`}>● {String(value || "draft").replaceAll("_", " ")}</span>;
const Notice = ({ short = false }) => <aside className="proprietary-notice" role="note">{short ? SHORT_PROPRIETARY_NOTICE : PROPRIETARY_NOTICE}</aside>;

const PATH_OPTIONS = [
  ["personal_productivity", "Personal Productivity"], ["citizen_development", "Citizen Development"],
  ["shared_internal_solution", "Shared Internal Solution"], ["platform_product_initiative", "Platform or Product Initiative"],
];
const blankAssessment = { working_name: "", business_problem: "", capabilities: "", company_id: "", intended_users: "", answers: {}, status: "in_progress" };

export function StartHere({ user, companies = [], assessments = [], drafts = [], onRegister, onExit, reload, notify = () => {}, admin = false }) {
  const mine = assessments.filter((item) => item.user_id === user?.id);
  const allMyDrafts = drafts.filter((item) => item.user_id === user?.id);
  const myDrafts = allMyDrafts.filter((item) => ["draft", "ready_for_submission"].includes(item.status));
  const [assessment, setAssessment] = useState(blankAssessment), [step, setStep] = useState(0), [dirty, setDirty] = useState(false), [saving, setSaving] = useState(false), [saved, setSaved] = useState("");
  const [override, setOverride] = useState(""), [overrideReason, setOverrideReason] = useState(""), [selectedType, setSelectedType] = useState("");
  const result = useMemo(() => classifyResource(assessment.answers, assessment), [assessment]);
  const totalSteps = 7;
  const update = (patch) => { setAssessment((current) => ({ ...current, ...patch })); setDirty(true); setSaved(""); };
  const answer = (key, value) => update({ answers: { ...assessment.answers, [key]: value } });
  useEffect(() => {
    const warn = (event) => { if (dirty) { event.preventDefault(); event.returnValue = ""; } };
    window.addEventListener("beforeunload", warn); return () => window.removeEventListener("beforeunload", warn);
  }, [dirty]);

  function databaseValues(status = assessment.status) {
    return {
      tenant_key: "lead-ventures", user_id: user.id, company_id: assessment.company_id || null, working_name: assessment.working_name.trim(),
      business_problem: assessment.business_problem.trim(), capabilities: assessment.capabilities.trim(), intended_users: assessment.intended_users.trim(),
      individual_use_response: assessment.answers.individual_use || null, multi_user_response: assessment.answers.multi_user || null,
      shared_data_response: assessment.answers.shared_data || null, technical_dependency_response: assessment.answers.technical_dependency || null,
      external_user_response: assessment.answers.external_users || null, commercial_intent_response: assessment.answers.commercial_intent || null,
      business_impact_response: assessment.answers.business_impact || null, support_response: assessment.answers.support_required || null,
      recommended_development_path: result.classification, recommended_resource_type: result.resourceType || null, recommendation_explanation: result.explanation,
      recommendation_factors: result.factors, rule_version: result.ruleVersion, override_classification: override || null, override_explanation: overrideReason.trim() || null, status,
    };
  }
  async function save(status = assessment.status) {
    if (assessment.status === "registered") { notify("Submitted assessment history is read-only. Start a new assessment to evaluate a changed scope."); return null; }
    setSaving(true);
    const values = databaseValues(status);
    const query = assessment.id ? supabase.from("start_here_assessments").update(values).eq("id", assessment.id).select().single() : supabase.from("start_here_assessments").insert(values).select().single();
    const { data, error } = await query; setSaving(false);
    if (error) { notify(`Assessment could not be saved: ${error.message}`); return null; }
    setAssessment((current) => ({ ...current, ...data, answers: current.answers, status })); setDirty(false); setSaved("Saved just now"); reload?.(); return data;
  }
  async function continueToRegister() {
    if (!onRegister) { notify("Your current role can use Start Here and save the assessment, but an Editor or Admin must create the registration draft."); return; }
    const type = selectedType || result.resourceType;
    if (!type) { notify("Choose Platform or Product before continuing."); return; }
    const completed = await save("completed"); if (!completed) return;
    const effective = { ...assessment, ...completed, selected_resource_type: type, override_classification: override || null };
    const formData = assessmentToRegistrationDraft(effective, result, { ...user, full_name: user.user_metadata?.full_name });
    const { data: draftId, error } = await supabase.rpc("convert_start_here_to_registration_draft", { target_assessment: completed.id, target_form_data: formData, target_selected_type: type });
    if (error) return notify(`Registration draft could not be created: ${error.message}`);
    setDirty(false); reload?.(); onRegister?.({ id: draftId, assessment_id: completed.id, user_id: user.id, company_id: effective.company_id, draft_form_data: formData, populated_fields: formData.populated_from_start_here, recommended_resource_type: result.resourceType, selected_resource_type: type, status: "draft" });
  }
  function resume(item) {
    const answers = { individual_use: item.individual_use_response, multi_user: item.multi_user_response, shared_data: item.shared_data_response, technical_dependency: item.technical_dependency_response, external_users: item.external_user_response, commercial_intent: item.commercial_intent_response, business_impact: item.business_impact_response, support_required: item.support_response };
    setAssessment({ ...item, answers }); setOverride(item.override_classification || ""); setOverrideReason(item.override_explanation || ""); setSelectedType(item.recommended_resource_type || ""); setStep(["completed", "registered"].includes(item.status) ? 6 : 0); setDirty(false); setSaved("");
  }
  async function abandon(item) {
    if (!window.confirm("Archive this abandoned assessment or draft?")) return;
    const table = item.assessment_id ? "resource_registration_drafts" : "start_here_assessments";
    const status = item.assessment_id ? "abandoned" : "archived";
    const { error } = await supabase.from(table).update({ status }).eq("id", item.id); if (error) return notify(error.message); reload?.();
  }
  async function remove(item) {
    if (!window.confirm("Permanently delete this abandoned item? This cannot be undone.")) return;
    const table = item.assessment_id ? "resource_registration_drafts" : "start_here_assessments";
    const { error } = await supabase.from(table).delete().eq("id", item.id); if (error) return notify(error.message);
    if (item.assessment_id) await supabase.from("start_here_assessments").update({ status: "completed", updated_at: new Date().toISOString() }).eq("id", item.assessment_id);
    reload?.();
  }
  function startOver() { if (!dirty || window.confirm("Discard unsaved answers and start over?")) { setAssessment(blankAssessment); setOverride(""); setOverrideReason(""); setSelectedType(""); setStep(0); setDirty(false); } }
  const canContinue = step === 0 ? assessment.working_name.trim() && assessment.business_problem.trim() : step === 1 ? assessment.capabilities.trim() && assessment.company_id && assessment.intended_users.trim() : step === 6 || CLASSIFICATION_QUESTIONS.slice((step - 2) * 2, (step - 1) * 2).every(({ key }) => assessment.answers[key]);
  const questionGroup = step >= 2 && step <= 5 ? CLASSIFICATION_QUESTIONS.slice((step - 2) * 2, (step - 1) * 2) : [];
  return <><div className="pagehead"><div><small>OPTIONAL BUILD GUIDANCE</small><h1>Start Here</h1><p>Clarify what you are planning to build. This assessment offers guidance; it is not permission or an approval gate.</p></div></div>
    {(mine.length > 0 || allMyDrafts.length > 0) && <section className="resume-panel"><h2>Resume your work</h2>{mine.filter((item) => ["in_progress", "completed"].includes(item.status)).map((item) => <div className="resume-row" key={item.id}><span><b>{item.working_name || "Untitled assessment"}</b><small>{item.status.replaceAll("_", " ")} · {new Date(item.updated_at).toLocaleDateString()}</small></span><button onClick={() => resume(item)}>Resume assessment</button><button onClick={() => abandon(item)}>Archive</button></div>)}{myDrafts.map((item) => <div className="resume-row" key={item.id}><span><b>{item.draft_form_data?.name || "Registration draft"}</b><small>Registration draft · {new Date(item.last_saved_at).toLocaleDateString()}</small></span><button className="primary" onClick={() => onRegister?.(item)}>Resume registration</button><button onClick={() => abandon(item)}>Abandon</button></div>)}{mine.filter((item) => item.status === "registered").map((item) => <div className="resume-row" key={item.id}><span><b>{item.working_name}</b><small>Registered · {item.override_classification || item.recommended_development_path} · rule {item.rule_version}</small></span><button onClick={() => resume(item)}>View recommendation</button></div>)}{[...mine.filter((item) => ["abandoned", "archived"].includes(item.status)), ...allMyDrafts.filter((item) => item.status === "abandoned")].map((item) => <div className="resume-row archived" key={`${item.assessment_id ? "draft" : "assessment"}-${item.id}`}><span><b>{item.working_name || item.draft_form_data?.name || "Abandoned draft"}</b><small>{item.status}</small></span><button onClick={() => remove(item)}>Delete</button></div>)}</section>}
    {admin && assessments.length > mine.length && <section className="resume-panel"><h2>Tenant assessment outcomes</h2><p className="muted">Operational planning view. Start Here remains guidance, not an approval queue.</p>{assessments.filter((item) => item.user_id !== user.id).slice(0, 12).map((item) => <div className="resume-row" key={item.id}><span><b>{item.working_name || "Untitled assessment"}</b><small>{item.override_classification || item.recommended_development_path || "In progress"} · {item.status} · rule {item.rule_version || "pending"}</small></span></div>)}</section>}
    <section className="assessment-wizard start-here" data-tour="start-here"><header><div><small>ASSESSMENT · RULE {result.ruleVersion}</small><h2>{step === 6 ? "Your recommendation" : "What are you creating?"}</h2></div><span>Step {step + 1} of {totalSteps}</span></header><div className="progress" aria-label={`Assessment progress: step ${step + 1} of ${totalSteps}`}><i style={{ width: `${((step + 1) / totalSteps) * 100}%` }} /></div>
      <div className="wizard-body">{step === 0 && <div className="wizard-fields"><label>Working name<input autoFocus value={assessment.working_name} onChange={(e) => update({ working_name: e.target.value })} placeholder="A short name for your idea" /></label><label>Business problem or goal<textarea value={assessment.business_problem} onChange={(e) => update({ business_problem: e.target.value })} placeholder="What should improve, and for whom?" /></label></div>}
      {step === 1 && <div className="wizard-fields"><label>Tasks or capabilities<textarea autoFocus value={assessment.capabilities} onChange={(e) => update({ capabilities: e.target.value })} placeholder="Describe the work it will perform or support" /></label><label>Company<select value={assessment.company_id} onChange={(e) => update({ company_id: e.target.value })}><option value="">Select a company</option>{companies.map((company) => <option key={company.id} value={company.id}>{company.name}</option>)}</select></label><label>Intended users<input value={assessment.intended_users} onChange={(e) => update({ intended_users: e.target.value })} placeholder="For example: me, Finance team, or customers" /></label></div>}
      {questionGroup.map(({ key, label, help }) => <fieldset className="wizard-question" key={key}><legend>{label}</legend><p>{help}</p><div>{["no", "unsure", "yes"].map((choice) => <label key={choice} className={assessment.answers[key] === choice ? "selected" : ""}><input type="radio" name={key} value={choice} checked={assessment.answers[key] === choice} onChange={() => answer(key, choice)} /><span>{choice[0].toUpperCase() + choice.slice(1)}</span></label>)}</div></fieldset>)}
      {step === 6 && <div className="result-grid"><article className="recommendation-card"><small>RECOMMENDED DEVELOPMENT PATH</small><h3>{result.label}</h3><p>{result.explanation}</p><dl><div><dt>Technical support</dt><dd>{result.technicalSupport ? "Expected" : "Not currently indicated"}</dd></div><div><dt>Admin or technical discussion</dt><dd>{result.adminDiscussion ? "Recommended for coordination" : result.unsureFactors.length ? "May be helpful" : "Not currently indicated"}</dd></div></dl><h4>Factors</h4><p>{result.factors.length ? result.factors.map((factor) => factor.replaceAll("_", " ")).join(", ") : "No higher-complexity factors selected."}</p>{result.unsureFactors.length > 0 && <p className="consultation-note"><b>Consultation may help:</b> {result.unsureFactors.join("; ")}. Unsure answers do not raise the classification automatically.</p>}<h4>Next steps</h4><ul>{result.nextSteps.map((item) => <li key={item}>{item}</li>)}</ul><h4>Governance considerations</h4><ul>{result.governance.map((item) => <li key={item}>{item}</li>)}</ul></article><aside className="result-actions"><label>Development path<select value={override || result.classification} onChange={(e) => setOverride(e.target.value)}>{PATH_OPTIONS.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label>{override && override !== result.classification && <label>Brief override explanation <span>(requested, not required)</span><textarea value={overrideReason} onChange={(e) => setOverrideReason(e.target.value)} /></label>}<label>Recommended resource type<select value={selectedType || result.resourceType} onChange={(e) => setSelectedType(e.target.value)}>{!selectedType && !result.resourceType && <option value="">Choose one</option>}{["agent", "skillset", "platform", "product"].map((type) => <option key={type} value={type}>{type[0].toUpperCase() + type.slice(1)}</option>)}</select></label><button className="primary" onClick={continueToRegister}>Continue to register</button><button onClick={() => setStep(0)}>Change my answers</button><button onClick={startOver}>Start over</button></aside></div>}</div>
      <footer><button disabled={step === 0} onClick={() => setStep((current) => Math.max(0, current - 1))}>Back</button><span aria-live="polite">{saving ? "Saving…" : saved}</span><button onClick={() => save()}>Save for later</button><button onClick={() => { if (!dirty || window.confirm("Exit with unsaved changes?")) onExit?.(); }}>Exit assessment</button>{step < 6 && <button className="primary" disabled={!canContinue} onClick={() => setStep((current) => current + 1)}>Continue</button>}</footer></section></>;
}

function StageEditor({ lifecycle, stages, phases, reload, notify }) {
  const [draft,setDraft]=useState(null);
  async function save(e){e.preventDefault(); const values={lifecycle_id:lifecycle.id,phase_id:draft.phase_id||null,parent_stage_id:draft.parent_stage_id||null,name:draft.name,stage_number:draft.stage_number||null,sequence:Number(draft.sequence)||1,purpose:draft.purpose||null,activities:(draft.activities||"").split("\n").filter(Boolean),entry_criteria:draft.entry_criteria||null,exit_criteria:draft.exit_criteria||null,accountable_owner_name:draft.accountable_owner_name||null,system_of_record:draft.system_of_record||null,success_metric:draft.success_metric||null,known_gaps:draft.known_gaps||null,created_by:draft.created_by||lifecycle.created_by,updated_by:lifecycle.created_by}; const query=draft.id?supabase.from("lifecycle_stages").update(values).eq("id",draft.id):supabase.from("lifecycle_stages").insert(values); const {error}=await query; if(error)return notify(error.message);setDraft(null);notify("Lifecycle stage saved.");reload();}
  async function remove(stage){let {error}=await supabase.rpc("delete_lifecycle_stage",{target_stage:stage.id,confirm_active_mappings:false});if(error?.message?.includes("active resource")&&window.confirm(`${error.message} Remove the mappings and delete the stage?`))({error}=await supabase.rpc("delete_lifecycle_stage",{target_stage:stage.id,confirm_active_mappings:true}));if(error)return notify(error.message);notify("Lifecycle stage deleted.");reload();}
  return <div className="stage-admin"><button onClick={()=>setDraft({name:"",sequence:stages.length+1,phase_id:phases[0]?.id||""})}>＋ Add stage</button>{stages.map((s,index)=><div className="stage-admin-row" key={s.id}><span>{s.stage_number||index+1}</span><b>{s.name}</b><small>{phases.find(p=>p.id===s.phase_id)?.name||"No phase"}</small><button onClick={()=>setDraft({...s,activities:(s.activities||[]).join("\n")})}>Edit</button><button className="danger" onClick={()=>remove(s)}>Delete</button></div>)}
  {draft&&<div className="backdrop"><form className="modal compact lifecycle-stage-form" onSubmit={save}><header><div><small>LIFECYCLE DESIGNER</small><h2>{draft.id?"Edit":"Add"} stage</h2></div><button type="button" onClick={()=>setDraft(null)}>×</button></header><label>Name<input required value={draft.name||""} onChange={e=>setDraft({...draft,name:e.target.value})}/></label><label>Sequence<input type="number" min="1" value={draft.sequence||1} onChange={e=>setDraft({...draft,sequence:e.target.value})}/></label><label>Phase<select value={draft.phase_id||""} onChange={e=>setDraft({...draft,phase_id:e.target.value})}><option value="">No phase</option>{phases.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>Parent stage<select value={draft.parent_stage_id||""} onChange={e=>setDraft({...draft,parent_stage_id:e.target.value})}><option value="">None</option>{stages.filter(s=>s.id!==draft.id).map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>Purpose<textarea value={draft.purpose||""} onChange={e=>setDraft({...draft,purpose:e.target.value})}/></label><label>Activities (one per line)<textarea value={draft.activities||""} onChange={e=>setDraft({...draft,activities:e.target.value})}/></label><label>Entry criteria<textarea value={draft.entry_criteria||""} onChange={e=>setDraft({...draft,entry_criteria:e.target.value})}/></label><label>Exit criteria<textarea value={draft.exit_criteria||""} onChange={e=>setDraft({...draft,exit_criteria:e.target.value})}/></label><label>Accountable owner<input value={draft.accountable_owner_name||""} onChange={e=>setDraft({...draft,accountable_owner_name:e.target.value})}/></label><label>System of record<input value={draft.system_of_record||""} onChange={e=>setDraft({...draft,system_of_record:e.target.value})}/></label><label>Success metric<input value={draft.success_metric||""} onChange={e=>setDraft({...draft,success_metric:e.target.value})}/></label><label>Known gaps or leakage<textarea value={draft.known_gaps||""} onChange={e=>setDraft({...draft,known_gaps:e.target.value})}/></label><footer><button type="button" onClick={()=>setDraft(null)}>Cancel</button><button className="primary">Save stage</button></footer></form></div>}</div>;
}

function PhaseConnectionAdmin({ lifecycle, phases, stages, connections, reload, notify }) {
 const [phaseName,setPhaseName]=useState(""),[from,setFrom]=useState(""),[to,setTo]=useState(""),[type,setType]=useState("feedback");
 async function addPhase(){if(!phaseName.trim())return;const {error}=await supabase.from("lifecycle_phases").insert({lifecycle_id:lifecycle.id,name:phaseName,sequence:phases.length+1,created_by:lifecycle.created_by,updated_by:lifecycle.created_by});if(error)return notify(error.message);setPhaseName("");notify("Lifecycle phase added.");reload();}
 async function renamePhase(phase){const name=window.prompt("Phase name",phase.name);if(!name)return;const sequence=Number(window.prompt("Phase sequence",phase.sequence))||phase.sequence;const {error}=await supabase.from("lifecycle_phases").update({name,sequence,updated_by:lifecycle.created_by}).eq("id",phase.id);if(error)return notify(error.message);reload();}
 async function addConnection(){if(!from||!to||from===to)return notify("Select two different stages.");const {error}=await supabase.from("lifecycle_connections").insert({lifecycle_id:lifecycle.id,from_stage_id:from,to_stage_id:to,connection_type:type,created_by:lifecycle.created_by,updated_by:lifecycle.created_by});if(error)return notify(error.message);setFrom("");setTo("");notify("Lifecycle connection added.");reload();}
 async function removeConnection(id){const {error}=await supabase.from("lifecycle_connections").delete().eq("id",id);if(error)return notify(error.message);reload();}
 return <section className="lifecycle-access"><h3>Phases and connections</h3><div className="phase-controls"><input placeholder="New phase name" value={phaseName} onChange={e=>setPhaseName(e.target.value)}/><button onClick={addPhase}>Add phase</button>{phases.map(p=><button key={p.id} onClick={()=>renamePhase(p)}>{p.sequence}. {p.name}</button>)}</div><div className="connection-controls"><select value={from} onChange={e=>setFrom(e.target.value)}><option value="">From stage</option>{stages.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select><select value={to} onChange={e=>setTo(e.target.value)}><option value="">To stage</option>{stages.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select><select value={type} onChange={e=>setType(e.target.value)}><option value="next">Next</option><option value="feedback">Feedback</option><option value="loop">Loop</option><option value="conditional">Conditional</option><option value="nested">Nested</option></select><button onClick={addConnection}>Connect stages</button></div>{connections.map(c=><button key={c.id} className="connection-chip" onClick={()=>removeConnection(c.id)}>{stages.find(s=>s.id===c.from_stage_id)?.name} → {stages.find(s=>s.id===c.to_stage_id)?.name} · {c.connection_type} ×</button>)}</section>;
}

function LifecycleGraph({ lifecycle, phases, stages, connections, mappings, resources }) {
  const [selected,setSelected]=useState(stages[0]||null), [list,setList]=useState(false);
  const ordered=[...stages].sort((a,b)=>a.sequence-b.sequence);
  const stageResources=(id)=>mappings.filter(m=>m.stage_id===id).map(m=>resources.find(r=>r.id===m.resource_id)).filter(Boolean);
  if(!stages.length)return <div className="empty lifecycle-empty"><h2>No stages yet</h2><p>Add stages to generate the visual lifecycle.</p></div>;
  return <><div className="viewer-toolbar"><button aria-pressed={!list} onClick={()=>setList(false)}>Graph view</button><button aria-pressed={list} onClick={()=>setList(true)}>Accessible list view</button></div>{list?<ol className="lifecycle-list">{ordered.map(stage=><li key={stage.id}><button onClick={()=>setSelected(stage)}><b>{stage.name}</b><span>{stage.purpose||"Purpose not documented"}</span></button></li>)}</ol>:<div className={`lifecycle-graph ${lifecycle.lifecycle_type}`} role="list" aria-label={`${lifecycle.name} stages`}>{ordered.map((stage,index)=>{const mapped=stageResources(stage.id);const nested=Boolean(stage.parent_stage_id);return <button role="listitem" key={stage.id} className={`lifecycle-node ${selected?.id===stage.id?"selected":""} ${!mapped.length?"gap":""} ${mapped.length>2?"overlap":""} ${nested?"nested":""}`} onClick={()=>setSelected(stage)} style={lifecycle.lifecycle_type==="circular"?{"--i":index,"--count":ordered.length}:undefined}><span>{stage.stage_number||index+1}</span><b>{stage.name}</b><small>{mapped.length?`${mapped.length} mapped resource${mapped.length===1?"":"s"}`:"Lifecycle gap"}</small></button>})}{connections.filter(c=>c.connection_type!=="next").map(c=><span className="connection-label" key={c.id}>{ordered.find(s=>s.id===c.from_stage_id)?.name} → {ordered.find(s=>s.id===c.to_stage_id)?.name}</span>)}</div>}
  {selected&&<article className="stage-detail"><small>SELECTED STAGE</small><h3>{selected.name}</h3><p>{selected.purpose||"Purpose has not been documented."}</p><dl><div><dt>Entry criteria</dt><dd>{selected.entry_criteria||"—"}</dd></div><div><dt>Exit criteria</dt><dd>{selected.exit_criteria||"—"}</dd></div><div><dt>Owner</dt><dd>{selected.accountable_owner_name||"—"}</dd></div><div><dt>System of record</dt><dd>{selected.system_of_record||"—"}</dd></div><div><dt>Success metric</dt><dd>{selected.success_metric||"—"}</dd></div><div><dt>Known gaps</dt><dd>{selected.known_gaps||"—"}</dd></div></dl><div className="mapped-resources">{stageResources(selected.id).map(r=><span className={`resource-chip ${r.entry_type}`} key={r.id}>{r.entry_type}: {r.name}</span>)}{!stageResources(selected.id).length&&<b className="gap-label">Unsupported lifecycle gap</b>}</div></article>}</>;
}

function LifecycleAccess({ lifecycle, users, viewers, reload, notify }) {
 const [scope,setScope]=useState(lifecycle.access_scope),[selected,setSelected]=useState(viewers.filter(v=>v.user_id).map(v=>v.user_id)),[selectedDepartments,setSelectedDepartments]=useState(viewers.filter(v=>v.department).map(v=>v.department));const departments=[...new Set(users.map(u=>u.department).filter(Boolean))];
 async function save(){const {error:e1}=await supabase.from("operational_lifecycles").update({access_scope:scope,updated_by:lifecycle.created_by}).eq("id",lifecycle.id);if(e1)return notify(e1.message);await supabase.from("lifecycle_viewers").delete().eq("lifecycle_id",lifecycle.id);let rows=[];if(scope==="selected_individuals")rows=selected.map(id=>({lifecycle_id:lifecycle.id,viewer_type:"user",user_id:id,created_by:lifecycle.created_by}));if(scope==="selected_departments")rows=selectedDepartments.map(department=>({lifecycle_id:lifecycle.id,viewer_type:"department",department,created_by:lifecycle.created_by}));if(rows.length){const {error}=await supabase.from("lifecycle_viewers").insert(rows);if(error)return notify(error.message);}notify("Lifecycle access updated.");reload();}
 return <section className="lifecycle-access"><h3>Lifecycle access</h3><dl><div><dt>Lifecycle</dt><dd>{lifecycle.name}</dd></div><div><dt>Company</dt><dd>{lifecycle.company_id}</dd></div><div><dt>Current scope</dt><dd>{lifecycle.access_scope.replaceAll("_"," ")}</dd></div><div><dt>Last changed by</dt><dd>{users.find(u=>u.id===lifecycle.updated_by)?.full_name||"Administrator"}</dd></div><div><dt>Last changed</dt><dd>{new Date(lifecycle.updated_at).toLocaleString()}</dd></div></dl><label>Who can view this lifecycle?<select value={scope} onChange={e=>setScope(e.target.value)}><option value="admins_only">Admins only</option><option value="entire_tenant">Entire tenant</option><option value="entire_company">Entire company</option><option value="selected_departments">Selected departments</option><option value="selected_individuals">Selected individuals</option></select></label>{scope==="selected_individuals"&&<div className="viewer-checks">{users.filter(u=>u.status==="active").map(u=><label key={u.id}><input type="checkbox" checked={selected.includes(u.id)} onChange={e=>setSelected(e.target.checked?[...selected,u.id]:selected.filter(id=>id!==u.id))}/>{u.full_name||u.email}{u.role==="admin"&&<small>Always has access</small>}</label>)}</div>}{scope==="selected_departments"&&<div className="viewer-checks">{departments.map(department=><label key={department}><input type="checkbox" checked={selectedDepartments.includes(department)} onChange={e=>setSelectedDepartments(e.target.checked?[...selectedDepartments,department]:selectedDepartments.filter(value=>value!==department))}/>{department}</label>)}</div>}<p>Sean and Danielle retain access through their active Admin role. Enforcement is applied by Supabase RLS.</p><button className="primary" onClick={save}>Save access</button></section>;
}

function AlignmentAdmin({ lifecycle, mappings, stages, resources, reload, notify }) {
 async function update(mapping,alignment_status){const admin_notes=window.prompt("Admin alignment notes:",mapping.admin_notes||"")||mapping.admin_notes||null;const {error}=await supabase.from("resource_lifecycle_mappings").update({alignment_status,admin_notes,approved_by:lifecycle.created_by,approved_at:new Date().toISOString(),mapping_source:"admin"}).eq("id",mapping.id);if(error)return notify(error.message);notify("Lifecycle alignment updated independently of governance risk.");reload();}
 const rows=mappings.filter(m=>m.lifecycle_id===lifecycle.id);return <section className="lifecycle-access"><h3>Resource-to-lifecycle alignment</h3><p>Creator selections, deterministic suggestions, and Admin decisions remain advisory and never change the governance score.</p>{!rows.length?<p>No resources are mapped. Unsupported stages remain visible as lifecycle gaps.</p>:rows.map(m=><div className="stage-admin-row" key={m.id}><span>{m.confidence==null?"—":`${m.confidence}%`}</span><b>{resources.find(r=>r.id===m.resource_id)?.name||"Resource"}</b><small>{stages.find(s=>s.id===m.stage_id)?.name||"Stage"}</small><select value={m.alignment_status} onChange={e=>update(m,e.target.value)}><option value="aligned">Aligned</option><option value="partially_aligned">Partially aligned</option><option value="alignment_needs_clarification">Alignment needs clarification</option><option value="not_currently_aligned">Not currently aligned</option><option value="not_applicable">Not applicable</option></select></div>)}</section>;
}

function LegacyLifecycles({ lifecycles, phases, stages, connections, mappings, viewers, companies, resources, users, admin, reload, notify }) {
 const [selectedId,setSelectedId]=useState(lifecycles[0]?.id||""),[creating,setCreating]=useState(false);const selected=lifecycles.find(l=>l.id===selectedId)||lifecycles[0];
 async function create(e){e.preventDefault();const form=new FormData(e.currentTarget);const {data,error}=await supabase.rpc("create_lifecycle_from_template",{target_company:form.get("company"),target_template:form.get("template"),target_name:form.get("name")});if(error)return notify(error.message);setCreating(false);setSelectedId(data);notify("Lifecycle created in Draft status.");reload();}
 async function status(value){const {error}=await supabase.rpc("set_lifecycle_status",{target_lifecycle:selected.id,target_status:value});if(error)return notify(error.message);notify(value==="archived"?"Lifecycle archived.":value==="active"?"Lifecycle published.":"Lifecycle restored to Draft.");reload();}
 async function version(){const {data,error}=await supabase.rpc("create_lifecycle_version",{source_lifecycle:selected.id});if(error)return notify(error.message);setSelectedId(data);notify("New lifecycle version created without changing the prior version.");reload();}
 async function changeType(lifecycle_type){const {error}=await supabase.from("operational_lifecycles").update({lifecycle_type,updated_by:selected.created_by}).eq("id",selected.id);if(error)return notify(error.message);notify("Lifecycle layout updated.");reload();}
 return <><div className="pagehead"><div><small>COMPANY OPERATIONS</small><h1>Operational Lifecycles</h1><p>Build and govern record-driven linear, circular, phased, nested, and hybrid lifecycle maps.</p></div>{admin&&<button className="primary" onClick={()=>setCreating(true)}>＋ Add lifecycle</button>}</div><Notice short/>
  {!selected?<div className="empty"><h2>No authorized lifecycles</h2><p>{admin?"Create a blank lifecycle or start from an optional template.":"An Admin can grant access to a company lifecycle."}</p></div>:<div className="lifecycle-workspace"><header><label>Lifecycle<select value={selected.id} onChange={e=>setSelectedId(e.target.value)}>{lifecycles.map(l=><option key={l.id} value={l.id}>{l.name} · v{l.version} · {l.status}</option>)}</select></label><div><Pill value={selected.status}/>{admin?<select aria-label="Lifecycle layout" value={selected.lifecycle_type} onChange={e=>changeType(e.target.value)}><option value="linear">Linear</option><option value="circular">Circular</option><option value="phased">Phased</option><option value="nested">Nested</option><option value="hybrid">Hybrid</option></select>:<span>{selected.lifecycle_type}</span>}{admin&&<><button onClick={version}>New version</button>{selected.status==="archived"?<button onClick={()=>status("draft")}>Restore</button>:<button onClick={()=>status("archived")}>Archive</button>}{selected.status!=="active"&&<button className="primary" onClick={()=>status("active")}>Publish</button>}</>}</div></header><p>{selected.description}</p><LifecycleGraph lifecycle={selected} phases={phases.filter(p=>p.lifecycle_id===selected.id)} stages={stages.filter(s=>s.lifecycle_id===selected.id)} connections={connections.filter(c=>c.lifecycle_id===selected.id)} mappings={mappings.filter(m=>m.lifecycle_id===selected.id)} resources={resources}/>{admin&&<><PhaseConnectionAdmin lifecycle={selected} phases={phases.filter(p=>p.lifecycle_id===selected.id)} stages={stages.filter(s=>s.lifecycle_id===selected.id)} connections={connections.filter(c=>c.lifecycle_id===selected.id)} reload={reload} notify={notify}/><StageEditor lifecycle={selected} phases={phases.filter(p=>p.lifecycle_id===selected.id)} stages={stages.filter(s=>s.lifecycle_id===selected.id)} reload={reload} notify={notify}/><AlignmentAdmin lifecycle={selected} mappings={mappings} stages={stages} resources={resources} reload={reload} notify={notify}/><LifecycleAccess lifecycle={selected} users={users} viewers={viewers.filter(v=>v.lifecycle_id===selected.id)} reload={reload} notify={notify}/></>}</div>}
 {creating&&<div className="backdrop"><form className="modal compact" onSubmit={create}><header><div><small>LIFECYCLE DESIGNER</small><h2>Add lifecycle</h2></div><button type="button" onClick={()=>setCreating(false)}>×</button></header><label>Name<input name="name" placeholder="Lifecycle name"/></label><label>Company<select name="company" required><option value="">Select company</option>{companies.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Start from<select name="template"><option value="blank">Blank lifecycle</option><option value="focusquest">FocusQuest starter template</option><option value="d9">D9 Network starter template</option></select></label><footer><button type="button" onClick={()=>setCreating(false)}>Cancel</button><button className="primary">Create draft</button></footer></form></div>}</>;
}

export function Lifecycles(props) { return <LifecycleExperience {...props}/>; }

export function DuplicateQueue({ matches, resources, notify, reload }) { const pending=matches.filter(m=>m.status==="pending"); async function resolve(match,status){const notes=window.prompt("Add review notes (optional):")||null;const {error}=await supabase.from("resource_duplicate_matches").update({status,admin_notes:notes,reviewed_by:match.created_by}).eq("id",match.id);if(error)return notify(error.message);notify("Duplicate review updated.");reload();} return <><div className="pagehead"><div><small>ADMIN REVIEW</small><h1>Potential Duplicates</h1><p>URL and keyword similarity warnings are reviewed separately from governance risk.</p></div></div>{!pending.length?<div className="empty"><h2>No pending duplicate matches</h2><p>Possible matches will appear here without blocking resource creation.</p></div>:<div className="cards duplicate-queue">{pending.map(m=>{const a=resources.find(r=>r.id===m.resource_id),b=resources.find(r=>r.id===m.matching_resource_id);return <article key={m.id}><small>{m.match_type.replaceAll("_"," ")} · {m.similarity_score}%</small><h3>{a?.name||"Resource"} ↔ {b?.name||"Possible match"}</h3><p>{(m.reasons||[]).join(" · ")}</p><p><b>Owners:</b> {a?.owner_name||"—"} / {b?.owner_name||"—"}</p><footer><button onClick={()=>resolve(m,"confirmed_distinct")}>Confirm distinct</button><button onClick={()=>resolve(m,"consolidation_requested")}>Request consolidation</button><button onClick={()=>resolve(m,"dismissed")}>Dismiss</button></footer></article>})}</div>}</>};

const COMPARE_FIELDS=[["Purpose",r=>r.purpose||r.description],["Capabilities",r=>r.skills_summary],["Users",r=>r.intended_users],["Company",r=>r.companies?.name],["Use",r=>r.use_audience],["Commercial potential",r=>r.commercial_status],["Integrations",r=>(r.integrations||[]).join(", ")],["Governance risk",r=>r.governance_score==null?"Pending":`${r.governance_score}%`],["Ownership",r=>r.owner_name],["Hosting",r=>`${r.hosting_environment||r.environment||"—"} · ${r.company_controlled_hosting===true?"company-controlled":r.company_controlled_hosting===false?"not company-controlled":"unverified"}`],["Stewardship",r=>r.stewardship_status],["Access",r=>r.access_scope]];
export function ResourceCompare({ resources }) {const [ids,setIds]=useState([]);const selected=ids.map(id=>resources.find(r=>r.id===id)).filter(Boolean);return <><div className="pagehead"><div><small>PORTFOLIO CLARITY</small><h1>Compare Resources</h1><p>Select two or more authorized resources to compare purpose, operations, governance, and stewardship.</p></div></div><div className="compare-picker">{resources.map(r=><label key={r.id}><input type="checkbox" checked={ids.includes(r.id)} onChange={e=>setIds(e.target.checked?[...ids,r.id]:ids.filter(id=>id!==r.id))}/>{r.name}</label>)}</div>{selected.length<2?<div className="empty"><h2>Select at least two resources</h2><p>The comparison uses only records you are authorized to retrieve.</p></div>:<div className="comparison-table"><table><thead><tr><th>Attribute</th>{selected.map(r=><th key={r.id}>{r.logo_url&&<img src={r.logo_url} alt=""/>}{r.name}<small>{r.entry_type}</small></th>)}</tr></thead><tbody>{COMPARE_FIELDS.map(([label,value])=><tr key={label}><th>{label}</th>{selected.map(r=><td key={r.id}>{value(r)||"—"}</td>)}</tr>)}</tbody></table></div>}</>};

function lifecycleLabel(product, mappings, relationships) {
  const mapped = mappings.filter(item => item.resource_id === product.id);
  const lifecycleLinks = relationships.filter(item => item.product_id === product.id && item.lifecycle_id);
  const lifecycleCount = new Set(mapped.map(item => item.lifecycle_id)).size;
  if (lifecycleCount > 1) return "Used across several company lifecycles";
  if (mapped.length) return "Mapped to one or more lifecycle stages";
  if (lifecycleLinks.length) return "Related to a lifecycle without belonging to a stage";
  if (product.lifecycle_relationship === "standalone_lead_ventures_product") return "Standalone Lead Ventures product";
  return "Not yet evaluated for lifecycle alignment";
}

export function ProductSuite({ resources, relationships, mappings, companies, lifecycles, admin, open, edit, reload, notify }) {
  const products=resources.filter(item=>item.entry_type==="product"), [view,setView]=useState("cards"),[search,setSearch]=useState(""),[family,setFamily]=useState("all"),[commercial,setCommercial]=useState("all"),[stage,setStage]=useState("all"),[company,setCompany]=useState("all"),[owner,setOwner]=useState("all"),[selected,setSelected]=useState(null),[compare,setCompare]=useState([]),[map,setMap]=useState(false),[relation,setRelation]=useState(false),[relationType,setRelationType]=useState("contains_platform");
  const families=[...new Set(products.map(p=>p.product_family).filter(Boolean))],owners=[...new Set(products.map(p=>p.owner_name).filter(Boolean))];
  const visible=products.filter(p=>(!search||`${p.name} ${p.description} ${p.product_family}`.toLowerCase().includes(search.toLowerCase()))&&(family==="all"||p.product_family===family)&&(commercial==="all"||p.commercial_status===commercial)&&(stage==="all"||p.development_stage===stage)&&(company==="all"||p.company_id===company)&&(owner==="all"||p.owner_name===owner));
  async function addRelation(e){e.preventDefault();const data=new FormData(e.currentTarget),type=data.get("type"),target=data.get("target");const values={product_id:selected.id,relationship_type:type,created_by:selected.created_by};if(type==="supports_company")values.company_id=target;else if(type==="supports_lifecycle")values.lifecycle_id=target;else values.related_resource_id=target;const {error}=await supabase.from("product_relationships").insert(values);if(error)return notify(error.message);setRelation(false);notify("Product relationship added.");reload();}
  const detail=selected&&products.find(p=>p.id===selected.id)||selected;
  return <><div className="pagehead"><div><small>LEAD VENTURES PORTFOLIO</small><h1>Lead Ventures Product Suite</h1><p>Commercial and strategic offerings, independent of company operational lifecycles.</p></div><div className="page-actions"><button onClick={()=>setMap(!map)}>Product Suite Map</button>{open&&<button className="primary" onClick={open}>＋ Add Product</button>}</div></div><Notice short/>
  <div className="product-filters"><input aria-label="Search products" placeholder="Search products" value={search} onChange={e=>setSearch(e.target.value)}/><select aria-label="Product family" value={family} onChange={e=>setFamily(e.target.value)}><option value="all">All product families</option>{families.map(x=><option key={x}>{x}</option>)}</select><select aria-label="Commercial status" value={commercial} onChange={e=>setCommercial(e.target.value)}><option value="all">All commercial statuses</option>{["internal_only","evaluating_commercial_potential","planned_commercial_product","pilot","commercially_available","retired"].map(x=><option key={x} value={x}>{x.replaceAll("_"," ")}</option>)}</select><select aria-label="Development stage" value={stage} onChange={e=>setStage(e.target.value)}><option value="all">All development stages</option>{["concept","discovery","mvp","pilot","production","scaling","retired"].map(x=><option key={x}>{x}</option>)}</select><select aria-label="Company" value={company} onChange={e=>setCompany(e.target.value)}><option value="all">All companies</option>{companies.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><select aria-label="Owner" value={owner} onChange={e=>setOwner(e.target.value)}><option value="all">All owners</option>{owners.map(x=><option key={x}>{x}</option>)}</select><button onClick={()=>setView(view==="cards"?"table":"cards")}>{view==="cards"?"Table view":"Card view"}</button></div>
  {map&&<section className="product-map" aria-label="Product Suite Map">{products.map((p,index)=><button key={p.id} style={{"--i":index}} onClick={()=>setSelected(p)}><b>{p.name}</b><small>{p.product_family||"Independent product"}</small></button>)}{relationships.map(r=><span key={r.id}>{products.find(p=>p.id===r.product_id)?.name} → {resources.find(x=>x.id===r.related_resource_id)?.name||companies.find(x=>x.id===r.company_id)?.name||lifecycles.find(x=>x.id===r.lifecycle_id)?.name}</span>)}</section>}
  {!visible.length?<div className="empty"><h2>No Products found</h2><p>Add a Product or change the filters.</p></div>:view==="cards"?<div className="product-groups">{[...new Set(visible.map(p=>p.product_family||"Standalone Products"))].map(group=><section key={group}><h2>{group}</h2><div className="product-cards">{visible.filter(p=>(p.product_family||"Standalone Products")===group).map(p=><article key={p.id}>{p.logo_url?<img src={p.logo_url} alt={`${p.name} logo`}/>:<i>{p.name.slice(0,2).toUpperCase()}</i>}<small>{p.commercial_status?.replaceAll("_"," ")}</small><h3>{p.name}</h3><p>{p.description}</p><b>{p.development_stage||"Stage not set"}</b><span>{lifecycleLabel(p,mappings,relationships)}</span><footer><button onClick={()=>setSelected(p)}>View details</button><label><input type="checkbox" checked={compare.includes(p.id)} onChange={e=>setCompare(e.target.checked?[...compare,p.id]:compare.filter(id=>id!==p.id))}/> Compare</label></footer></article>)}</div></section>)}</div>:<div className="comparison-table"><table><thead><tr><th>Product</th><th>Family</th><th>Company</th><th>Owner</th><th>Commercial status</th><th>Development</th><th>Lifecycle relationship</th></tr></thead><tbody>{visible.map(p=><tr key={p.id} onClick={()=>setSelected(p)}><td>{p.name}</td><td>{p.product_family||"—"}</td><td>{p.companies?.name||"—"}</td><td>{p.owner_name}</td><td>{p.commercial_status?.replaceAll("_"," ")}</td><td>{p.development_stage||"—"}</td><td>{lifecycleLabel(p,mappings,relationships)}</td></tr>)}</tbody></table></div>}
  {compare.length>=2&&<ResourceCompare resources={products.filter(p=>compare.includes(p.id))}/>} {detail&&<div className="backdrop"><section className="modal compact product-detail" role="dialog" aria-modal="true"><header><div><small>PRODUCT DETAILS</small><h2>{detail.name}</h2></div><button onClick={()=>setSelected(null)}>×</button></header><Notice short/><dl><div><dt>Business problem</dt><dd>{detail.purpose||detail.description}</dd></div><div><dt>Owner / creator</dt><dd>{detail.owner_name} / {detail.original_creator||"—"}</dd></div><div><dt>Target market</dt><dd>{detail.target_market||"—"}</dd></div><div><dt>Commercial / development</dt><dd>{detail.commercial_status?.replaceAll("_"," ")} · {detail.development_stage||"—"}</dd></div><div><dt>Lifecycle</dt><dd>{lifecycleLabel(detail,mappings,relationships)}</dd></div><div><dt>Related resources</dt><dd>{relationships.filter(r=>r.product_id===detail.id).map(r=>resources.find(x=>x.id===r.related_resource_id)?.name).filter(Boolean).join(", ")||"—"}</dd></div></dl><footer>{admin&&<button onClick={()=>setRelation(true)}>Add relationship</button>}{edit&&<button className="primary" onClick={()=>{setSelected(null);edit(detail)}}>Edit Product</button>}<button onClick={()=>setSelected(null)}>Close</button></footer></section></div>}
  {relation&&<div className="backdrop"><form className="modal compact" onSubmit={addRelation}><header><h2>Add Product relationship</h2><button type="button" onClick={()=>setRelation(false)}>×</button></header><label>Relationship<select name="type" value={relationType} onChange={e=>setRelationType(e.target.value)}>{["contains_platform","contains_agent","uses_skillset","integrates_with_product","supports_company","supports_lifecycle","powers_product","shared_component"].map(x=><option key={x} value={x}>{x.replaceAll("_"," ")}</option>)}</select></label><label>Related record<select name="target" required><option value="">Select record</option>{relationType==="supports_company"?companies.map(c=><option key={c.id} value={c.id}>company: {c.name}</option>):relationType==="supports_lifecycle"?lifecycles.map(l=><option key={l.id} value={l.id}>lifecycle: {l.name}</option>):resources.filter(r=>r.id!==selected?.id).map(r=><option key={r.id} value={r.id}>{r.entry_type}: {r.name}</option>)}</select></label><footer><button type="button" onClick={()=>setRelation(false)}>Cancel</button><button className="primary">Add relationship</button></footer></form></div>}</>;
}

export { Notice };
