import { useMemo, useState } from "react";
import { supabase } from "./supabase";
import { CLASSIFICATION_QUESTIONS, classifyResource } from "./classification";
import { PROPRIETARY_NOTICE, SHORT_PROPRIETARY_NOTICE } from "./lifecycles";

const Pill = ({ value }) => <span className={`pill ${value}`}>● {String(value || "draft").replaceAll("_", " ")}</span>;
const Notice = ({ short = false }) => <aside className="proprietary-notice" role="note">{short ? SHORT_PROPRIETARY_NOTICE : PROPRIETARY_NOTICE}</aside>;

export function StartHere({ onCreate }) {
  const [answers, setAnswers] = useState({}), [accepted, setAccepted] = useState(""), [reason, setReason] = useState("");
  const result = useMemo(() => classifyResource(answers), [answers]);
  return <section className="start-here" data-tour="start-here">
    <header><div><small>START HERE</small><h2>What are you creating?</h2><p>Answer a few plain-language questions. The recommendation is deterministic and does not use an external AI service.</p></div><b>{result.label}</b></header>
    <div className="guidance-grid"><div className="guidance-questions">{CLASSIFICATION_QUESTIONS.map(([key,label]) => <fieldset key={key}><legend>{label}</legend><label><input type="radio" name={key} checked={answers[key]===true} onChange={() => setAnswers({...answers,[key]:true})}/> Yes</label><label><input type="radio" name={key} checked={answers[key]===false} onChange={() => setAnswers({...answers,[key]:false})}/> No</label></fieldset>)}</div>
      <aside className="recommendation-card"><small>RECOMMENDED CLASSIFICATION</small><h3>{result.label}</h3><p>{result.explanation}</p><h4>Suggested next steps</h4><ul>{result.nextSteps.map((item) => <li key={item}>{item}</li>)}</ul><h4>Governance considerations</h4><ul>{result.governance.map((item) => <li key={item}>{item}</li>)}</ul><p><b>Technical support:</b> {result.technicalSupport ? "Involve technical support." : "Not currently indicated; reassess if scope grows."}</p>
      <label>Classification choice<select value={accepted || result.classification} onChange={(e) => setAccepted(e.target.value)}><option value="citizen_development">Employee Upskilling / Citizen Development</option><option value="shared_internal">Shared Internal Resource</option><option value="platform">Platform</option><option value="product">Product</option></select></label>{accepted && accepted!==result.classification && <label>Why is a different classification appropriate?<textarea required value={reason} onChange={(e) => setReason(e.target.value)}/></label>}
      <button className="primary" disabled={accepted && accepted!==result.classification && !reason.trim()} onClick={() => onCreate?.({ assessment:result, answers, accepted:accepted||result.classification, reason })}>Accept and register resource</button></aside></div>
  </section>;
}

function StageEditor({ lifecycle, stages, phases, reload, notify }) {
  const [draft,setDraft]=useState(null);
  async function save(e){e.preventDefault(); const values={lifecycle_id:lifecycle.id,phase_id:draft.phase_id||null,parent_stage_id:draft.parent_stage_id||null,name:draft.name,stage_number:draft.stage_number||null,sequence:Number(draft.sequence)||1,purpose:draft.purpose||null,activities:(draft.activities||"").split("\n").filter(Boolean),entry_criteria:draft.entry_criteria||null,exit_criteria:draft.exit_criteria||null,accountable_owner_name:draft.accountable_owner_name||null,system_of_record:draft.system_of_record||null,success_metric:draft.success_metric||null,known_gaps:draft.known_gaps||null,created_by:draft.created_by||lifecycle.created_by,updated_by:lifecycle.created_by}; const query=draft.id?supabase.from("lifecycle_stages").update(values).eq("id",draft.id):supabase.from("lifecycle_stages").insert(values); const {error}=await query; if(error)return notify(error.message);setDraft(null);notify("Lifecycle stage saved.");reload();}
  async function remove(stage){let {error}=await supabase.rpc("delete_lifecycle_stage",{target_stage:stage.id,confirm_active_mappings:false});if(error?.message?.includes("active resource")&&window.confirm(`${error.message} Remove the mappings and delete the stage?`))({error}=await supabase.rpc("delete_lifecycle_stage",{target_stage:stage.id,confirm_active_mappings:true}));if(error)return notify(error.message);notify("Lifecycle stage deleted.");reload();}
  return <div className="stage-admin"><button onClick={()=>setDraft({name:"",sequence:stages.length+1,phase_id:phases[0]?.id||""})}>＋ Add stage</button>{stages.map((s,index)=><div className="stage-admin-row" key={s.id}><span>{s.stage_number||index+1}</span><b>{s.name}</b><small>{phases.find(p=>p.id===s.phase_id)?.name||"No phase"}</small><button onClick={()=>setDraft({...s,activities:(s.activities||[]).join("\n")})}>Edit</button><button className="danger" onClick={()=>remove(s)}>Delete</button></div>)}
  {draft&&<div className="backdrop"><form className="modal compact lifecycle-stage-form" onSubmit={save}><header><div><small>LIFECYCLE DESIGNER</small><h2>{draft.id?"Edit":"Add"} stage</h2></div><button type="button" onClick={()=>setDraft(null)}>×</button></header><label>Name<input required value={draft.name||""} onChange={e=>setDraft({...draft,name:e.target.value})}/></label><label>Sequence<input type="number" min="1" value={draft.sequence||1} onChange={e=>setDraft({...draft,sequence:e.target.value})}/></label><label>Phase<select value={draft.phase_id||""} onChange={e=>setDraft({...draft,phase_id:e.target.value})}><option value="">No phase</option>{phases.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>Parent stage<select value={draft.parent_stage_id||""} onChange={e=>setDraft({...draft,parent_stage_id:e.target.value})}><option value="">None</option>{stages.filter(s=>s.id!==draft.id).map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>Purpose<textarea value={draft.purpose||""} onChange={e=>setDraft({...draft,purpose:e.target.value})}/></label><label>Activities (one per line)<textarea value={draft.activities||""} onChange={e=>setDraft({...draft,activities:e.target.value})}/></label><label>Entry criteria<textarea value={draft.entry_criteria||""} onChange={e=>setDraft({...draft,entry_criteria:e.target.value})}/></label><label>Exit criteria<textarea value={draft.exit_criteria||""} onChange={e=>setDraft({...draft,exit_criteria:e.target.value})}/></label><label>Accountable owner<input value={draft.accountable_owner_name||""} onChange={e=>setDraft({...draft,accountable_owner_name:e.target.value})}/></label><label>System of record<input value={draft.system_of_record||""} onChange={e=>setDraft({...draft,system_of_record:e.target.value})}/></label><label>Success metric<input value={draft.success_metric||""} onChange={e=>setDraft({...draft,success_metric:e.target.value})}/></label><label>Known gaps or leakage<textarea value={draft.known_gaps||""} onChange={e=>setDraft({...draft,known_gaps:e.target.value})}/></label><footer><button type="button" onClick={()=>setDraft(null)}>Cancel</button><button className="primary">Save stage</button></footer></form></div>}</div>;
}

function PhaseConnectionAdmin({ lifecycle, phases, stages, connections, reload, notify }) {
 const [phaseName,setPhaseName]=useState(""),[from,setFrom]=useState(""),[to,setTo]=useState(""),[type,setType]=useState("feedback");
 async function addPhase(){if(!phaseName.trim())return;const {error}=await supabase.from("lifecycle_phases").insert({lifecycle_id:lifecycle.id,name:phaseName,sequence:phases.length+1,created_by:lifecycle.created_by,updated_by:lifecycle.created_by});if(error)return notify(error.message);setPhaseName("");notify("Lifecycle phase added.");reload();}
 async function renamePhase(phase){const name=window.prompt("Phase name",phase.name);if(!name)return;const sequence=Number(window.prompt("Phase sequence",phase.sequence))||phase.sequence;const {error}=await supabase.from("lifecycle_phases").update({name,sequence,updated_by:lifecycle.created_by}).eq("id",phase.id);if(error)return notify(error.message);reload();}
 async function addConnection(){if(!from||!to||from===to)return notify("Select two different stages.");const {error}=await supabase.from("lifecycle_connections").insert({lifecycle_id:lifecycle.id,from_stage_id:from,to_stage_id:to,connection_type:type,created_by:lifecycle.created_by,updated_by:lifecycle.created_by});if(error)return notify(error.message);setFrom("");setTo("");notify("Lifecycle connection added.");reload();}
 async function removeConnection(id){const {error}=await supabase.from("lifecycle_connections").delete().eq("id",id);if(error)return notify(error.message);reload();}
 return <section className="lifecycle-access"><h3>Phases and connections</h3><div className="phase-controls"><input placeholder="New phase name" value={phaseName} onChange={e=>setPhaseName(e.target.value)}/><button onClick={addPhase}>Add phase</button>{phases.map(p=><button key={p.id} onClick={()=>renamePhase(p)}>{p.sequence}. {p.name}</button>)}</div><div className="connection-controls"><select value={from} onChange={e=>setFrom(e.target.value)}><option value="">From stage</option>{stages.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select><select value={to} onChange={e=>setTo(e.target.value)}><option value="">To stage</option>{stages.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select><select value={type} onChange={e=>setType(e.target.value)}><option value="next">Next</option><option value="feedback">Feedback</option><option value="loop">Loop</option><option value="conditional">Conditional</option><option value="nested">Nested</option></select><button onClick={addConnection}>Connect stages</button></div>{connections.map(c=><button key={c.id} className="connection-chip" onClick={()=>removeConnection(c.id)}>{stages.find(s=>s.id===c.from_stage_id)?.name} → {stages.find(s=>s.id===c.to_stage_id)?.name} · {c.connection_type} ×</button>)}</section>;
}

function LifecycleGraph({ lifecycle, phases, stages, connections, mappings, resources }) {
  const [selected,setSelected]=useState(stages[0]||null), [list,setList]=useState(false);
  const ordered=[...stages].sort((a,b)=>a.sequence-b.sequence);
  const stageResources=(id)=>mappings.filter(m=>m.stage_id===id).map(m=>resources.find(r=>r.id===m.resource_id)).filter(Boolean);
  if(!stages.length)return <div className="empty lifecycle-empty"><h2>No stages yet</h2><p>Add stages to generate the visual lifecycle.</p></div>;
  return <><div className="viewer-toolbar"><button aria-pressed={!list} onClick={()=>setList(false)}>Graph view</button><button aria-pressed={list} onClick={()=>setList(true)}>Accessible list view</button></div>{list?<ol className="lifecycle-list">{ordered.map(stage=><li key={stage.id}><button onClick={()=>setSelected(stage)}><b>{stage.name}</b><span>{stage.purpose||"Purpose not documented"}</span></button></li>)}</ol>:<div className={`lifecycle-graph ${lifecycle.lifecycle_type}`} role="list" aria-label={`${lifecycle.name} stages`}>{ordered.map((stage,index)=>{const mapped=stageResources(stage.id);const nested=Boolean(stage.parent_stage_id);return <button role="listitem" key={stage.id} className={`lifecycle-node ${selected?.id===stage.id?"selected":""} ${!mapped.length?"gap":""} ${mapped.length>2?"overlap":""} ${nested?"nested":""}`} onClick={()=>setSelected(stage)} style={lifecycle.lifecycle_type==="circular"?{"--i":index,"--count":ordered.length}:undefined}><span>{stage.stage_number||index+1}</span><b>{stage.name}</b><small>{mapped.length?`${mapped.length} mapped resource${mapped.length===1?"":"s"}`:"Lifecycle gap"}</small></button>})}{connections.filter(c=>c.connection_type!=="next").map(c=><span className="connection-label" key={c.id}>{ordered.find(s=>s.id===c.from_stage_id)?.name} → {ordered.find(s=>s.id===c.to_stage_id)?.name}</span>)}</div>}
  {selected&&<article className="stage-detail"><small>SELECTED STAGE</small><h3>{selected.name}</h3><p>{selected.purpose||"Purpose has not been documented."}</p><dl><div><dt>Entry criteria</dt><dd>{selected.entry_criteria||"—"}</dd></div><div><dt>Exit criteria</dt><dd>{selected.exit_criteria||"—"}</dd></div><div><dt>Owner</dt><dd>{selected.accountable_owner_name||"—"}</dd></div><div><dt>System of record</dt><dd>{selected.system_of_record||"—"}</dd></div><div><dt>Success metric</dt><dd>{selected.success_metric||"—"}</dd></div><div><dt>Known gaps</dt><dd>{selected.known_gaps||"—"}</dd></div></dl><div className="mapped-resources">{stageResources(selected.id).map(r=><span className={`resource-chip ${r.entry_type}`} key={r.id}>{r.entry_type}: {r.name}</span>)}{!stageResources(selected.id).length&&<b className="gap-label">Unsupported lifecycle gap</b>}</div></article>}</>;
}

function LifecycleAccess({ lifecycle, users, viewers, reload, notify }) {
 const [scope,setScope]=useState(lifecycle.access_scope),[selected,setSelected]=useState(viewers.filter(v=>v.user_id).map(v=>v.user_id)),[selectedDepartments,setSelectedDepartments]=useState(viewers.filter(v=>v.department).map(v=>v.department));const departments=[...new Set(users.map(u=>u.department).filter(Boolean))];
 async function save(){const {error:e1}=await supabase.from("operational_lifecycles").update({access_scope:scope,updated_by:lifecycle.created_by}).eq("id",lifecycle.id);if(e1)return notify(e1.message);await supabase.from("lifecycle_viewers").delete().eq("lifecycle_id",lifecycle.id);let rows=[];if(scope==="selected_individuals")rows=selected.map(id=>({lifecycle_id:lifecycle.id,viewer_type:"user",user_id:id,created_by:lifecycle.created_by}));if(scope==="selected_departments")rows=selectedDepartments.map(department=>({lifecycle_id:lifecycle.id,viewer_type:"department",department,created_by:lifecycle.created_by}));if(rows.length){const {error}=await supabase.from("lifecycle_viewers").insert(rows);if(error)return notify(error.message);}notify("Lifecycle access updated.");reload();}
 return <section className="lifecycle-access"><h3>Lifecycle access</h3><dl><div><dt>Lifecycle</dt><dd>{lifecycle.name}</dd></div><div><dt>Company</dt><dd>{lifecycle.company_id}</dd></div><div><dt>Current scope</dt><dd>{lifecycle.access_scope.replaceAll("_"," ")}</dd></div><div><dt>Last changed by</dt><dd>{users.find(u=>u.id===lifecycle.updated_by)?.full_name||"Administrator"}</dd></div><div><dt>Last changed</dt><dd>{new Date(lifecycle.updated_at).toLocaleString()}</dd></div></dl><label>Who can view this lifecycle?<select value={scope} onChange={e=>setScope(e.target.value)}><option value="admins_only">Admins only</option><option value="entire_tenant">Entire tenant</option><option value="entire_company">Entire company</option><option value="selected_departments">Selected departments</option><option value="selected_individuals">Selected individuals</option></select></label>{scope==="selected_individuals"&&<div className="viewer-checks">{users.filter(u=>u.status==="active").map(u=><label key={u.id}><input type="checkbox" checked={selected.includes(u.id)} onChange={e=>setSelected(e.target.checked?[...selected,u.id]:selected.filter(id=>id!==u.id))}/>{u.full_name||u.email}{u.role==="admin"&&<small>Always has access</small>}</label>)}</div>}{scope==="selected_departments"&&<div className="viewer-checks">{departments.map(department=><label key={department}><input type="checkbox" checked={selectedDepartments.includes(department)} onChange={e=>setSelectedDepartments(e.target.checked?[...selectedDepartments,department]:selectedDepartments.filter(value=>value!==department))}/>{department}</label>)}</div>}<p>Sean and Danielle retain access through their active Admin role. Enforcement is applied by Supabase RLS.</p><button className="primary" onClick={save}>Save access</button></section>;
}

function AlignmentAdmin({ lifecycle, mappings, stages, resources, reload, notify }) {
 async function update(mapping,alignment_status){const admin_notes=window.prompt("Admin alignment notes:",mapping.admin_notes||"")||mapping.admin_notes||null;const {error}=await supabase.from("resource_lifecycle_mappings").update({alignment_status,admin_notes,approved_by:lifecycle.created_by,approved_at:new Date().toISOString(),mapping_source:"admin"}).eq("id",mapping.id);if(error)return notify(error.message);notify("Lifecycle alignment updated independently of governance risk.");reload();}
 const rows=mappings.filter(m=>m.lifecycle_id===lifecycle.id);return <section className="lifecycle-access"><h3>Resource-to-lifecycle alignment</h3><p>Creator selections, deterministic suggestions, and Admin decisions remain advisory and never change the governance score.</p>{!rows.length?<p>No resources are mapped. Unsupported stages remain visible as lifecycle gaps.</p>:rows.map(m=><div className="stage-admin-row" key={m.id}><span>{m.confidence==null?"—":`${m.confidence}%`}</span><b>{resources.find(r=>r.id===m.resource_id)?.name||"Resource"}</b><small>{stages.find(s=>s.id===m.stage_id)?.name||"Stage"}</small><select value={m.alignment_status} onChange={e=>update(m,e.target.value)}><option value="aligned">Aligned</option><option value="partially_aligned">Partially aligned</option><option value="alignment_needs_clarification">Alignment needs clarification</option><option value="not_currently_aligned">Not currently aligned</option><option value="not_applicable">Not applicable</option></select></div>)}</section>;
}

export function Lifecycles({ lifecycles, phases, stages, connections, mappings, viewers, companies, resources, users, admin, reload, notify }) {
 const [selectedId,setSelectedId]=useState(lifecycles[0]?.id||""),[creating,setCreating]=useState(false);const selected=lifecycles.find(l=>l.id===selectedId)||lifecycles[0];
 async function create(e){e.preventDefault();const form=new FormData(e.currentTarget);const {data,error}=await supabase.rpc("create_lifecycle_from_template",{target_company:form.get("company"),target_template:form.get("template"),target_name:form.get("name")});if(error)return notify(error.message);setCreating(false);setSelectedId(data);notify("Lifecycle created in Draft status.");reload();}
 async function status(value){const {error}=await supabase.rpc("set_lifecycle_status",{target_lifecycle:selected.id,target_status:value});if(error)return notify(error.message);notify(value==="archived"?"Lifecycle archived.":value==="active"?"Lifecycle published.":"Lifecycle restored to Draft.");reload();}
 async function version(){const {data,error}=await supabase.rpc("create_lifecycle_version",{source_lifecycle:selected.id});if(error)return notify(error.message);setSelectedId(data);notify("New lifecycle version created without changing the prior version.");reload();}
 async function changeType(lifecycle_type){const {error}=await supabase.from("operational_lifecycles").update({lifecycle_type,updated_by:selected.created_by}).eq("id",selected.id);if(error)return notify(error.message);notify("Lifecycle layout updated.");reload();}
 return <><div className="pagehead"><div><small>COMPANY OPERATIONS</small><h1>Operational Lifecycles</h1><p>Build and govern record-driven linear, circular, phased, nested, and hybrid lifecycle maps.</p></div>{admin&&<button className="primary" onClick={()=>setCreating(true)}>＋ Add lifecycle</button>}</div><Notice short/>
  {!selected?<div className="empty"><h2>No authorized lifecycles</h2><p>{admin?"Create a blank lifecycle or start from an optional template.":"An Admin can grant access to a company lifecycle."}</p></div>:<div className="lifecycle-workspace"><header><label>Lifecycle<select value={selected.id} onChange={e=>setSelectedId(e.target.value)}>{lifecycles.map(l=><option key={l.id} value={l.id}>{l.name} · v{l.version} · {l.status}</option>)}</select></label><div><Pill value={selected.status}/>{admin?<select aria-label="Lifecycle layout" value={selected.lifecycle_type} onChange={e=>changeType(e.target.value)}><option value="linear">Linear</option><option value="circular">Circular</option><option value="phased">Phased</option><option value="nested">Nested</option><option value="hybrid">Hybrid</option></select>:<span>{selected.lifecycle_type}</span>}{admin&&<><button onClick={version}>New version</button>{selected.status==="archived"?<button onClick={()=>status("draft")}>Restore</button>:<button onClick={()=>status("archived")}>Archive</button>}{selected.status!=="active"&&<button className="primary" onClick={()=>status("active")}>Publish</button>}</>}</div></header><p>{selected.description}</p><LifecycleGraph lifecycle={selected} phases={phases.filter(p=>p.lifecycle_id===selected.id)} stages={stages.filter(s=>s.lifecycle_id===selected.id)} connections={connections.filter(c=>c.lifecycle_id===selected.id)} mappings={mappings.filter(m=>m.lifecycle_id===selected.id)} resources={resources}/>{admin&&<><PhaseConnectionAdmin lifecycle={selected} phases={phases.filter(p=>p.lifecycle_id===selected.id)} stages={stages.filter(s=>s.lifecycle_id===selected.id)} connections={connections.filter(c=>c.lifecycle_id===selected.id)} reload={reload} notify={notify}/><StageEditor lifecycle={selected} phases={phases.filter(p=>p.lifecycle_id===selected.id)} stages={stages.filter(s=>s.lifecycle_id===selected.id)} reload={reload} notify={notify}/><AlignmentAdmin lifecycle={selected} mappings={mappings} stages={stages} resources={resources} reload={reload} notify={notify}/><LifecycleAccess lifecycle={selected} users={users} viewers={viewers.filter(v=>v.lifecycle_id===selected.id)} reload={reload} notify={notify}/></>}</div>}
 {creating&&<div className="backdrop"><form className="modal compact" onSubmit={create}><header><div><small>LIFECYCLE DESIGNER</small><h2>Add lifecycle</h2></div><button type="button" onClick={()=>setCreating(false)}>×</button></header><label>Name<input name="name" placeholder="Lifecycle name"/></label><label>Company<select name="company" required><option value="">Select company</option>{companies.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Start from<select name="template"><option value="blank">Blank lifecycle</option><option value="focusquest">FocusQuest starter template</option><option value="d9">D9 Network starter template</option></select></label><footer><button type="button" onClick={()=>setCreating(false)}>Cancel</button><button className="primary">Create draft</button></footer></form></div>}</>;
}

export function DuplicateQueue({ matches, resources, notify, reload }) { const pending=matches.filter(m=>m.status==="pending"); async function resolve(match,status){const notes=window.prompt("Add review notes (optional):")||null;const {error}=await supabase.from("resource_duplicate_matches").update({status,admin_notes:notes,reviewed_by:match.created_by}).eq("id",match.id);if(error)return notify(error.message);notify("Duplicate review updated.");reload();} return <><div className="pagehead"><div><small>ADMIN REVIEW</small><h1>Potential Duplicates</h1><p>URL and keyword similarity warnings are reviewed separately from governance risk.</p></div></div>{!pending.length?<div className="empty"><h2>No pending duplicate matches</h2><p>Possible matches will appear here without blocking resource creation.</p></div>:<div className="cards duplicate-queue">{pending.map(m=>{const a=resources.find(r=>r.id===m.resource_id),b=resources.find(r=>r.id===m.matching_resource_id);return <article key={m.id}><small>{m.match_type.replaceAll("_"," ")} · {m.similarity_score}%</small><h3>{a?.name||"Resource"} ↔ {b?.name||"Possible match"}</h3><p>{(m.reasons||[]).join(" · ")}</p><p><b>Owners:</b> {a?.owner_name||"—"} / {b?.owner_name||"—"}</p><footer><button onClick={()=>resolve(m,"confirmed_distinct")}>Confirm distinct</button><button onClick={()=>resolve(m,"consolidation_requested")}>Request consolidation</button><button onClick={()=>resolve(m,"dismissed")}>Dismiss</button></footer></article>})}</div>}</>};

const COMPARE_FIELDS=[["Purpose",r=>r.purpose||r.description],["Capabilities",r=>r.skills_summary],["Users",r=>r.intended_users],["Company",r=>r.companies?.name],["Use",r=>r.use_audience],["Commercial potential",r=>r.commercial_status],["Integrations",r=>(r.integrations||[]).join(", ")],["Governance risk",r=>r.governance_score==null?"Pending":`${r.governance_score}%`],["Ownership",r=>r.owner_name],["Hosting",r=>`${r.hosting_environment||r.environment||"—"} · ${r.company_controlled_hosting===true?"company-controlled":r.company_controlled_hosting===false?"not company-controlled":"unverified"}`],["Stewardship",r=>r.stewardship_status],["Access",r=>r.access_scope]];
export function ResourceCompare({ resources }) {const [ids,setIds]=useState([]);const selected=ids.map(id=>resources.find(r=>r.id===id)).filter(Boolean);return <><div className="pagehead"><div><small>PORTFOLIO CLARITY</small><h1>Compare Resources</h1><p>Select two or more authorized resources to compare purpose, operations, governance, and stewardship.</p></div></div><div className="compare-picker">{resources.map(r=><label key={r.id}><input type="checkbox" checked={ids.includes(r.id)} onChange={e=>setIds(e.target.checked?[...ids,r.id]:ids.filter(id=>id!==r.id))}/>{r.name}</label>)}</div>{selected.length<2?<div className="empty"><h2>Select at least two resources</h2><p>The comparison uses only records you are authorized to retrieve.</p></div>:<div className="comparison-table"><table><thead><tr><th>Attribute</th>{selected.map(r=><th key={r.id}>{r.logo_url&&<img src={r.logo_url} alt=""/>}{r.name}<small>{r.entry_type}</small></th>)}</tr></thead><tbody>{COMPARE_FIELDS.map(([label,value])=><tr key={label}><th>{label}</th>{selected.map(r=><td key={r.id}>{value(r)||"—"}</td>)}</tr>)}</tbody></table></div>}</>};

function lifecycleLabel(product, mappings, relationships) {
  const mapped = mappings.filter(item => item.resource_id === product.id);
  const lifecycleLinks = relationships.filter(item => item.product_id === product.id && item.lifecycle_id);
  const lifecycleCount = new Set(mapped.map(item => item.lifecycle_id)).size;
  if (lifecycleCount > 1) return "Used across several company lifecycles";
  if (mapped.length) return "Mapped to one or more lifecycle stages";
  if (lifecycleLinks.length) return "Related to a lifecycle without belonging to a stage";
  if (product.lifecycle_relationship === "standalone_lead_ventures_product") return "Standalone Lead Ventures product";
  return "Not yet evaluated for lifecycle alignment";
}

export function ProductSuite({ resources, relationships, mappings, companies, lifecycles, admin, open, edit, reload, notify }) {
  const products=resources.filter(item=>item.entry_type==="product"), [view,setView]=useState("cards"),[search,setSearch]=useState(""),[family,setFamily]=useState("all"),[commercial,setCommercial]=useState("all"),[stage,setStage]=useState("all"),[company,setCompany]=useState("all"),[owner,setOwner]=useState("all"),[selected,setSelected]=useState(null),[compare,setCompare]=useState([]),[map,setMap]=useState(false),[relation,setRelation]=useState(false),[relationType,setRelationType]=useState("contains_platform");
  const families=[...new Set(products.map(p=>p.product_family).filter(Boolean))],owners=[...new Set(products.map(p=>p.owner_name).filter(Boolean))];
  const visible=products.filter(p=>(!search||`${p.name} ${p.description} ${p.product_family}`.toLowerCase().includes(search.toLowerCase()))&&(family==="all"||p.product_family===family)&&(commercial==="all"||p.commercial_status===commercial)&&(stage==="all"||p.development_stage===stage)&&(company==="all"||p.company_id===company)&&(owner==="all"||p.owner_name===owner));
  async function addRelation(e){e.preventDefault();const data=new FormData(e.currentTarget),type=data.get("type"),target=data.get("target");const values={product_id:selected.id,relationship_type:type,created_by:selected.created_by};if(type==="supports_company")values.company_id=target;else if(type==="supports_lifecycle")values.lifecycle_id=target;else values.related_resource_id=target;const {error}=await supabase.from("product_relationships").insert(values);if(error)return notify(error.message);setRelation(false);notify("Product relationship added.");reload();}
  const detail=selected&&products.find(p=>p.id===selected.id)||selected;
  return <><div className="pagehead"><div><small>LEAD VENTURES PORTFOLIO</small><h1>Lead Ventures Product Suite</h1><p>Commercial and strategic offerings, independent of company operational lifecycles.</p></div><div className="page-actions"><button onClick={()=>setMap(!map)}>Product Suite Map</button>{open&&<button className="primary" onClick={open}>＋ Add Product</button>}</div></div><Notice short/>
  <div className="product-filters"><input aria-label="Search products" placeholder="Search products" value={search} onChange={e=>setSearch(e.target.value)}/><select aria-label="Product family" value={family} onChange={e=>setFamily(e.target.value)}><option value="all">All product families</option>{families.map(x=><option key={x}>{x}</option>)}</select><select aria-label="Commercial status" value={commercial} onChange={e=>setCommercial(e.target.value)}><option value="all">All commercial statuses</option>{["internal_only","evaluating_commercial_potential","planned_commercial_product","pilot","commercially_available","retired"].map(x=><option key={x} value={x}>{x.replaceAll("_"," ")}</option>)}</select><select aria-label="Development stage" value={stage} onChange={e=>setStage(e.target.value)}><option value="all">All development stages</option>{["concept","discovery","mvp","pilot","production","scaling","retired"].map(x=><option key={x}>{x}</option>)}</select><select aria-label="Company" value={company} onChange={e=>setCompany(e.target.value)}><option value="all">All companies</option>{companies.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><select aria-label="Owner" value={owner} onChange={e=>setOwner(e.target.value)}><option value="all">All owners</option>{owners.map(x=><option key={x}>{x}</option>)}</select><button onClick={()=>setView(view==="cards"?"table":"cards")}>{view==="cards"?"Table view":"Card view"}</button></div>
  {map&&<section className="product-map" aria-label="Product Suite Map">{products.map((p,index)=><button key={p.id} style={{"--i":index}} onClick={()=>setSelected(p)}><b>{p.name}</b><small>{p.product_family||"Independent product"}</small></button>)}{relationships.map(r=><span key={r.id}>{products.find(p=>p.id===r.product_id)?.name} → {resources.find(x=>x.id===r.related_resource_id)?.name||companies.find(x=>x.id===r.company_id)?.name||lifecycles.find(x=>x.id===r.lifecycle_id)?.name}</span>)}</section>}
  {!visible.length?<div className="empty"><h2>No Products found</h2><p>Add a Product or change the filters.</p></div>:view==="cards"?<div className="product-groups">{[...new Set(visible.map(p=>p.product_family||"Standalone Products"))].map(group=><section key={group}><h2>{group}</h2><div className="product-cards">{visible.filter(p=>(p.product_family||"Standalone Products")===group).map(p=><article key={p.id}>{p.logo_url?<img src={p.logo_url} alt={`${p.name} logo`}/>:<i>{p.name.slice(0,2).toUpperCase()}</i>}<small>{p.commercial_status?.replaceAll("_"," ")}</small><h3>{p.name}</h3><p>{p.description}</p><b>{p.development_stage||"Stage not set"}</b><span>{lifecycleLabel(p,mappings,relationships)}</span><footer><button onClick={()=>setSelected(p)}>View details</button><label><input type="checkbox" checked={compare.includes(p.id)} onChange={e=>setCompare(e.target.checked?[...compare,p.id]:compare.filter(id=>id!==p.id))}/> Compare</label></footer></article>)}</div></section>)}</div>:<div className="comparison-table"><table><thead><tr><th>Product</th><th>Family</th><th>Company</th><th>Owner</th><th>Commercial status</th><th>Development</th><th>Lifecycle relationship</th></tr></thead><tbody>{visible.map(p=><tr key={p.id} onClick={()=>setSelected(p)}><td>{p.name}</td><td>{p.product_family||"—"}</td><td>{p.companies?.name||"—"}</td><td>{p.owner_name}</td><td>{p.commercial_status?.replaceAll("_"," ")}</td><td>{p.development_stage||"—"}</td><td>{lifecycleLabel(p,mappings,relationships)}</td></tr>)}</tbody></table></div>}
  {compare.length>=2&&<ResourceCompare resources={products.filter(p=>compare.includes(p.id))}/>} {detail&&<div className="backdrop"><section className="modal compact product-detail" role="dialog" aria-modal="true"><header><div><small>PRODUCT DETAILS</small><h2>{detail.name}</h2></div><button onClick={()=>setSelected(null)}>×</button></header><Notice short/><dl><div><dt>Business problem</dt><dd>{detail.purpose||detail.description}</dd></div><div><dt>Owner / creator</dt><dd>{detail.owner_name} / {detail.original_creator||"—"}</dd></div><div><dt>Target market</dt><dd>{detail.target_market||"—"}</dd></div><div><dt>Commercial / development</dt><dd>{detail.commercial_status?.replaceAll("_"," ")} · {detail.development_stage||"—"}</dd></div><div><dt>Lifecycle</dt><dd>{lifecycleLabel(detail,mappings,relationships)}</dd></div><div><dt>Related resources</dt><dd>{relationships.filter(r=>r.product_id===detail.id).map(r=>resources.find(x=>x.id===r.related_resource_id)?.name).filter(Boolean).join(", ")||"—"}</dd></div></dl><footer>{admin&&<button onClick={()=>setRelation(true)}>Add relationship</button>}{edit&&<button className="primary" onClick={()=>{setSelected(null);edit(detail)}}>Edit Product</button>}<button onClick={()=>setSelected(null)}>Close</button></footer></section></div>}
  {relation&&<div className="backdrop"><form className="modal compact" onSubmit={addRelation}><header><h2>Add Product relationship</h2><button type="button" onClick={()=>setRelation(false)}>×</button></header><label>Relationship<select name="type" value={relationType} onChange={e=>setRelationType(e.target.value)}>{["contains_platform","contains_agent","uses_skillset","integrates_with_product","supports_company","supports_lifecycle","powers_product","shared_component"].map(x=><option key={x} value={x}>{x.replaceAll("_"," ")}</option>)}</select></label><label>Related record<select name="target" required><option value="">Select record</option>{relationType==="supports_company"?companies.map(c=><option key={c.id} value={c.id}>company: {c.name}</option>):relationType==="supports_lifecycle"?lifecycles.map(l=><option key={l.id} value={l.id}>lifecycle: {l.name}</option>):resources.filter(r=>r.id!==selected?.id).map(r=><option key={r.id} value={r.id}>{r.entry_type}: {r.name}</option>)}</select></label><footer><button type="button" onClick={()=>setRelation(false)}>Cancel</button><button className="primary">Add relationship</button></footer></form></div>}</>;
}

export { Notice };
